<a href="https://colab.research.google.com/github/pujitha9908/python_data_visualization/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**What is NumPy?**



NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

**Why Use NumPy?**

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

**NumPy Creating Arrays**

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

 We can create a NumPy ndarray object by using the array() function.



In [ ]:
import numpy as np

In [ ]:
p = np.array([1,2,3,4,5])
print(p)
print(type(p))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Dimensions of an array in NumPy are also called the Rank of an Array.

Here, we will see how to check how many dimensions an array has used with the  numpy.ndarray.ndim. With that, we will also see some examples of creating 0D, 1D, 2D, and 3D arrays:

Create a 0-Dimensional NumPy array and check the dimensions

Create a 1-Dimensional NumPy array and check the dimensions

Create a 2-Dimensional NumPy array and check the dimensions

Create a 3-Dimensional NumPy array and check the dimensions

In [ ]:
# 0-D array
import numpy as np

n = np.array(25)
print(n)

25


In [ ]:
# one - dimensional array

import numpy as np

n = np.array([10, 20, 30])
print(n)

[10 20 30]


In [ ]:
#2-dimensional array
import numpy as np

n = np.array([[1,3,5],[4,8,12]])
print(n)

[[ 1  3  5]
 [ 4  8 12]]


In [ ]:
#3-Dimensional array
import numpy as np

n = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(n)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**Initialize Numpy arrays**

To Initialize NumPy arrays, use the  numpy.zeros() method. Using this method, initialize numpy arrays with zeros. Let us see some examples.

Initialize numpy arrays with zeros
Let us see an example to initialize numpy arrays with zeros. We are creating a 2×3 array with zeros:


In [ ]:
# intially zeros 2 rows and 3columns
import numpy as np

n = np.zeros([2, 3])
print(n)
print(type(n))


[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
n = np.ones([4,4])
print(n)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Datatypes in Numpy**


b – boolean

u – unsigned integer

f – float

c – complex float

m – timedelta

M – datetime

O – object

S – string

U – unicode string

Let us see some examples:

Get the datatype of a NumPy array with integers

Get the datatype of a NumPy array with strings

Set the datatype size within a NumPy array

Convert one datatype to another

In [ ]:
#Get the datatype of a Numpy array with integers
#To get the datatype of a Numpy array, use the dtype attribute. Let us see an example:
n = np.array([1,2,3,4])
print(n.dtype)

int64


In [ ]:
#string data type
import numpy as np

n = np.array(["amit", "rohit", "ashwin", "jadeja", "virat"])
print(n.dtype)

<U6


**Convert one datatype to another**

Use the astype() to create a copy of an array and then set the new data type.

 This is how you can convert one type to another.

In the example, we have an array of strings.

 We will convert it to an integer, with i as a parameter as shown below:



In [ ]:
#converting one data type in to another data type
import numpy as np

n = np.array(['10', '20', '30', '40', '50'])
print(n)
print(n.dtype)

n2 = n.astype('i')
print(n2)
print(n2.dtype)

['10' '20' '30' '40' '50']
<U2
[10 20 30 40 50]
int32


**Slicing arrays**

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: **[start:end].**

We can also define the step, like this: **[start:end:step].**

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [ ]:
#negative slicing
arr = np.array([1,2,3,4,5,6])
print(arr[-5:-1])

[2 3 4 5]


In [ ]:
#start:end:step
arr = np.array([1,2,3,4,5,6])
print(arr[1:4:2])

[2 4]


In [ ]:
p = np.array([1,2,3,4,5,6,7])
print(arr[::3])

[1 4]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


**The Difference Between Copy and View**

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.


The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.


The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



In [ ]:
#copying the array to the new variable
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#viewing the present array
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


**Check if Array Owns its Data**


Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
y = arr.copy()

print(x.base)
print(y.base)

[1 2 3 4 5]
None



**Shape of an Array **

The shape of an array is the number of elements in each dimension.

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


**Reshaping arrays**

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)  # 2 matrics , 3rows,2columns

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**Iterating Arrays**

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [ ]:
#iterating the 1-D array
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [ ]:
#iterating the 2-D array

arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in arr:
  print(x)

[1 2 3 4]
[5 6 7 8]


In [ ]:
#iterating the three array
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
  for y in x:
    for z in y:
        print(z)

1
2
3
4
5
6
7
8
9
10
11
12


**Iterating Arrays Using nditer()**

The function nditer() is a helping function that can be used from very basic to very advanced iterations.

 It solves some basic issues which we face in iteration, lets go through it with examples.

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


**Splitting NumPy Arrays**

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])


[1 2]
[3 4]
[5 6]


In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 4)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


**Searching Arrays**

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
x = np.where(arr==3)
print(x)

(array([2]),)


In [ ]:
#Find the indexes where the values are even:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [ ]:
#Find the indexes where the values are odd:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


**Sorting Arrays**

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [ ]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


[0 1 2 3]


In [ ]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))


[False  True  True]
